"use client";
import { useEffect, useState } from "react";

type Match = { id: string; status: string; participant1?: { id: string; name: string }; participant2?: { id: string; name: string }; score: { games: { participant1: number; participant2: number; completed: boolean }[]; currentGame: number; status: string; winnerId?: string } };
export function BadmintonScorer({ matchId, initial }: { matchId: string; initial: Match }) { const [match, setMatch] = useState(initial); const [error, setError] = useState(""); const game = match.score.games[match.score.currentGame];
  async function act(body: object) { setError(""); const response = await fetch(`/api/badminton/matches/${matchId}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "Score rejected"); return; } setMatch(data.match); }
  useEffect(() => { const timer = setInterval(async () => { const response = await fetch(`/api/badminton/matches/${matchId}`); if (response.ok) setMatch((await response.json()).match); }, 4000); return () => clearInterval(timer); }, [matchId]);
  const walkover = match.status === "walkover";
  return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="mb-5 flex items-center justify-between"><span className="text-xs uppercase tracking-widest text-emerald-300">{walkover ? "Walkover" : match.score.status === "live" ? "Live" : match.score.status}</span><button disabled={walkover} onClick={() => act({ action: "undo" })} className="rounded-lg border border-white/15 px-3 py-2 text-sm disabled:opacity-40">Undo</button></div><div className="grid grid-cols-[1fr_auto] gap-3 text-lg"><div>{match.participant1?.name ?? "TBD"}</div><strong className="text-4xl text-emerald-300">{game?.participant1 ?? 0}</strong><div>{match.participant2?.name ?? "TBD"}</div><strong className="text-4xl text-amber-300">{game?.participant2 ?? 0}</strong></div><p className="mt-4 text-sm text-white/50">{walkover ? `${match.participant1?.name ?? match.participant2?.name} advances automatically` : <>Game {match.score.currentGame + 1} of {match.score.games.length}{match.score.winnerId ? " · Match complete" : ""}</>}</p><div className="mt-5 grid grid-cols-2 gap-3"><button disabled={walkover || !match.participant1 || !!match.score.winnerId} onClick={() => act({ action: "point", winnerId: match.participant1?.id })} className="rounded-xl bg-emerald-400 px-3 py-4 font-bold text-emerald-950 disabled:opacity-40">+1 {match.participant1?.name ?? "Player 1"}</button><button disabled={walkover || !match.participant2 || !!match.score.winnerId} onClick={() => act({ action: "point", winnerId: match.participant2?.id })} className="rounded-xl bg-amber-300 px-3 py-4 font-bold text-amber-950 disabled:opacity-40">+1 {match.participant2?.name ?? "Player 2"}</button></div>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</div>;
}